# Generated by Django 4.1.3 on 2022-11-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceNameSub', models.CharField(max_length=64)),
                ('webhook', models.URLField()),
                ('serviceNamePub', models.CharField(max_length=64)),
            ],
        ),
    ]
