# Generated by Django 4.1.3 on 2022-11-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0003_alter_messagemodel_options"),
        ("subscribers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribermodel",
            name="serviceNamePub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="publisher.messagemodel",
                verbose_name="serviceNamePub",
            ),
        ),
    ]
