# Generated by Django 4.1.3 on 2022-11-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0002_alter_subscribermodel_servicenamepub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribermodel",
            name="id",
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
