# Generated by Django 4.1.3 on 2022-11-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0003_alter_subscribermodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribermodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
