# Generated by Django 4.1.3 on 2022-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0005_alter_subscribermodel_servicenamepub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribermodel",
            name="serviceNamePub",
            field=models.CharField(max_length=64),
        ),
    ]
