# Generated by Django 4.1.3 on 2022-11-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0009_alter_messagemodel_servicenamepub"),
        ("subscribers", "0008_alter_subscribermodel_servicenamepub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribermodel",
            name="serviceNamePub",
            field=models.ForeignKey(
                default="IT",
                on_delete=django.db.models.deletion.CASCADE,
                to="publisher.messagemodel",
                to_field="serviceNamePub",
            ),
        ),
    ]
