# Generated by Django 4.1.3 on 2022-11-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceNamePub', models.CharField(max_length=64)),
                ('data', models.JSONField()),
                ('datetimeMutation', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
