# Generated by Django 4.1.3 on 2022-11-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0002_messagemodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagemodel",
            options={"verbose_name": "serviceNamePub"},
        ),
    ]
