# Generated by Django 4.1.3 on 2022-11-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0003_alter_messagemodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagemodel",
            name="id",
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
