# Generated by Django 4.1.3 on 2022-11-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0004_alter_messagemodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagemodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
