# Generated by Django 4.1.3 on 2022-11-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0007_alter_messagemodel_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagemodel",
            options={},
        ),
    ]
