# Generated by Django 4.1.3 on 2022-11-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0008_alter_messagemodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagemodel",
            name="serviceNamePub",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
