version: '3.8'

services: 
  app:
    image: docker-django-v0.1 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      -.:/code
    ports:
      -"8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      -.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pubsub
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    container_name: postgres_db


    
    

  